# Generated by Django 4.2.3 on 2023-07-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('status', models.BooleanField()),
                ('server_port', models.IntegerField()),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
