# Generated by Django 4.2.3 on 2023-07-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_instancemetric'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instancemetric',
            table='instance_metrics',
        ),
    ]
