# Generated by Django 4.2.3 on 2023-07-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_instancemetric_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancemetric',
            old_name='disk_usgae',
            new_name='disk_usage',
        ),
    ]
