# Generated by Django 4.2.3 on 2023-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_rename_disk_usgae_instancemetric_disk_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='container_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='hostname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
