# Generated by Django 4.2.3 on 2023-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_instance_container_id_instance_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployHost',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('container_id', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=6)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deploy_host',
            },
        ),
    ]
