# Generated by Django 4.2.3 on 2023-08-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_deployhost_host_name_deployhost_ip_deployhost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployhost',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
