# Generated by Django 4.2.3 on 2023-08-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_deployhost_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployhost',
            name='status',
            field=models.CharField(default='OFFLINE', max_length=15),
        ),
    ]
