# Generated by Django 4.2.3 on 2023-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_deployhost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostRegisterInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_type', models.CharField(max_length=2)),
                ('vm_ip', models.CharField(max_length=15)),
                ('pm_ip', models.CharField(max_length=15)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'host_register_info',
            },
        ),
    ]
