version: "2"
services:
   sqoop:
      image: mayi21docker/sqoop:1.4.7.1
      hostname: sqoop
      command: ["/bin/bash"]
      environment:
        JAVA_HOME: /usr/lib/java-1.8.0/jdk
      env_file:
        - ./config
      volumes:
        - /Users/xaohii/data/docker_local/share:/share
      stdin_open: true
      tty: true
      networks:
        - big_data-network
networks:
  # 使用之前先确保这个网络段存在
  big_data-network:
    external: true