version: "2"
services:
   hiveBaseHadoop:
      image: mayi21docker/jdk:hive
      environment:
        HADOOP_HOME: /opt/hadoop
        MYSQL_URL: jdbc:mysql://mysql:3306/metastore_db_4
        MYSQL_USER: root
        MYSQL_PASSWD: 123456
        DRIVER_URL: com.mysql.cj.jdbc.Driver
      ports:
        - 9872:9870
        - 8090:8088
        - 50072:50070
        - 10002:10000
        - 10003:10001
      volumes:
        - /Users/xaohii/data/docker_local/share:/share
      networks:
        - big_data-network
networks:
  big_data-network:
    external: true