version: "2"
services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      command: ["hdfs", "namenode"]
      environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
        HADOOP_HOME: /opt/hadoop
      ports:
        - 9870:9870
      env_file:
        - ./config
      networks:
        - big_data-network
   datanode:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      environment:
        HADOOP_HOME: /opt/hadoop
      env_file:
        - ./config
      networks:
        - big_data-network
   resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      environment:
        HADOOP_HOME: /opt/hadoop
      ports:
         - 8088:8088
      env_file:
        - ./config
      networks:
        - big_data-network
   nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      environment:
        HADOOP_HOME: /opt/hadoop
      env_file:
        - ./config
      volumes:
        - /Users/xaohii/data/docker_local/share:/tmp
      networks:
        - big_data-network
   hadoop-client:
      image: apache/hadoop:3
      hostname: hadoop-client
      command: ["/bin/bash"]
      env_file:
        - ./config
      volumes:
        - /Users/xaohii/data/docker_local/share:/tmp
      stdin_open: true
      tty: true
      networks:
        - big_data-network
networks:
  big_data-network:
    external: true