# Generated by Django 4.2.3 on 2025-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=255, verbose_name='IP地址')),
                ('sn', models.CharField(max_length=255, verbose_name='设备SN')),
                ('updateTime', models.BigIntegerField(verbose_name='更新时间戳')),
            ],
            options={
                'verbose_name': 'Agent信息',
                'verbose_name_plural': 'Agent信息',
                'db_table': 'agent_info',
            },
        ),
    ]
