version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - C:\Users\xaohii\data\local_data\mysql:/var/lib/mysql
      - C:\Users\xaohii\data\share:/share
    ports:
      - 7306:3306
    networks:
      - big_data-network

networks:
  big_data-network:
    external: true