version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /Users/xaohii/data/docker_local/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306