version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /Users/xaohii/data/docker_local/mysql_data:/var/lib/mysql
      - /Users/xaohii/data/docker_local/share:/share
    ports:
      - 3306:3306
    networks:
      - big_data-network

networks:
  big_data-network:
    external: true